// seaData.js
export const seaData = {
    'Red Sea': {
      gigatonnesIceLoss: '10 Gt',
      seaLevelEquivalent: '0.5 mm',
      massBalance: '-1.2 Gt/year',
      iceFlowVelocity: '200 m/year',
      glacierLengthChanges: '-5 km',
      icebergCalvingRates: '50 Gt/year',
      globalMeanSeaLevel: '3.2 mm/year',
      regionalSeaLevelChange: '4.0 mm/year',
      rateOfSeaLevelRise: '1.5 mm/year',
      surfaceTemperature: '25°C',
      precipitation: '100 mm/year',
      oceanTemperature: '22°C',
    },
    'Black Sea': {
      gigatonnesIceLoss: '5 Gt',
      seaLevelEquivalent: '0.3 mm',
      massBalance: '-0.8 Gt/year',
      iceFlowVelocity: '150 m/year',
      glacierLengthChanges: '-3 km',
      icebergCalvingRates: '30 Gt/year',
      globalMeanSeaLevel: '2.8 mm/year',
      regionalSeaLevelChange: '3.5 mm/year',
      rateOfSeaLevelRise: '1.2 mm/year',
      surfaceTemperature: '20°C',
      precipitation: '120 mm/year',
      oceanTemperature: '18°C',
    },
    'Arabian Sea': {
      gigatonnesIceLoss: '8 Gt',
      seaLevelEquivalent: '0.4 mm',
      massBalance: '-1.0 Gt/year',
      iceFlowVelocity: '180 m/year',
      glacierLengthChanges: '-4 km',
      icebergCalvingRates: '40 Gt/year',
      globalMeanSeaLevel: '3.0 mm/year',
      regionalSeaLevelChange: '3.8 mm/year',
      rateOfSeaLevelRise: '1.4 mm/year',
      surfaceTemperature: '28°C',
      precipitation: '80 mm/year',
      oceanTemperature: '26°C',
    },
    'Caribbean Sea': {
      gigatonnesIceLoss: '6 Gt',
      seaLevelEquivalent: '0.3 mm',
      massBalance: '-0.8 Gt/year',
      iceFlowVelocity: '150 m/year',
      glacierLengthChanges: '-3.5 km',
      icebergCalvingRates: '35 Gt/year',
      globalMeanSeaLevel: '2.8 mm/year',
      regionalSeaLevelChange: '3.5 mm/year',
      rateOfSeaLevelRise: '1.2 mm/year',
      surfaceTemperature: '27°C',
      precipitation: '85 mm/year',
      oceanTemperature: '27°C',
    },

  };